version: "3.8"

services:
  mysql:
    image: mysql:5.7
    build: ./src/db
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_HOST=%
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - $MYSQLDB_DOCKER_PORT
    # volumes:
    #   - db:/var/lib/mysql
  app:
    depends_on:
      - mysql
    build: .
    restart: unless-stopped
    env_file: ./.env
    # command: ["./wait-for-it.sh", "mysql:3306"]
    # command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    ports:
      - 3000:3000
    environment:
      - WAIT_HOSTS=mysql:3306
      - DB_HOST=mysql
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
# volumes:
#   db:
